package com.example.pokescanner.model

import com.example.pokescanner.R

class LoadPkmnData {
    fun LoadData(): List<Pkmn> {
        return listOf<Pkmn>(
            Pkmn(1, "Bulbasaur", listOf<String>("Grass", "Poison"), "A strange seed was planted on its back at birth. The plant sprouts and grows with this POKéMON.", R.drawable.bulbasaur),
            Pkmn(2, "Ivysaur", listOf<String>("Grass", "Poison"), "When the bulb on its back grows large, it appears to lose the ability to stand on its hind legs.", R.drawable.ivysaur),
            Pkmn(3, "Venusaur", listOf<String>("Grass", "Poison"), "0003", R.drawable.venusaur),
            Pkmn(4, "Charmander", listOf<String>("Fire"), "Obviously prefers hot places. When it rains, steam is said to spout from the tip of its tail.", R.drawable.charmander),
            Pkmn(5, "Charmeleon", listOf<String>("Fire"), "When it swings its burning tail, it elevates the temperature to unbearably high levels.", R.drawable.charmeleon),
            Pkmn(6, "Charizard", listOf<String>("Fire", "Flying"), "0006", R.drawable.charizard),
            Pkmn(7, "Squirtle", listOf<String>("Water"), "After birth, its back swells and hardens into a shell. Powerfully sprays foam from its mouth.", R.drawable.squirtle),
            Pkmn(8, "Wartortle", listOf<String>("Water"), "Often hides in water to stalk unwary prey. For swimming fast, it moves its ears to maintain balance.", R.drawable.wartortle),
            Pkmn(9, "Blastoise", listOf<String>("Water"), "0009", R.drawable.blastoise),
            Pkmn(10, "Caterpie", listOf<String>("Bug"), "Its short feet are tipped with suction pads that enable it to tirelessly climb slopes and walls.", R.drawable.caterpie),
            Pkmn(11, "Metapod", listOf<String>("Bug"), "This POKéMON is vulnerable to attack while its shell is soft, exposing its weak and tender body.", R.drawable.metapod),
            Pkmn(12, "Butterfree", listOf<String>("Bug", "Flying"), "In battle, it flaps its wings at high speed to release highly toxic dust into the air.", R.drawable.butterfree),
            Pkmn(13, "Weedle", listOf<String>("Bug", "Poison"), "Often found in forests, eating leaves. It has a sharp venomous stinger on its head.", R.drawable.weedle),
            Pkmn(14, "Kakuna", listOf<String>("Bug", "Poison"), "Almost incapable of moving, this POKéMON can only harden its shell to protect itself from predators.", R.drawable.kakuna),
            Pkmn(15, "Beedrill", listOf<String>("Bug", "Poison"), "0015", R.drawable.beedrill),
            Pkmn(16, "Pidgey", listOf<String>("Normal", "Flying"), "A common sight in forests and woods. It flaps its wings at ground level to kick up blinding sand.", R.drawable.pidgey),
            Pkmn(17, "Pidgeotto", listOf<String>("Normal", "Flying"), "Very protective of its sprawling territorial area, this POKéMON will fiercely peck at any intruder.", R.drawable.pidgeotto),
            Pkmn(18, "Pidgeot", listOf<String>("Normal", "Flying"), "0018", R.drawable.pidgeot),
            Pkmn(19, "Rattata", listOf<String>("Normal"), "0019", R.drawable.rattata),
            Pkmn(20, "Raticate", listOf<String>("Normal"), "0020", R.drawable.raticate),
            Pkmn(21, "Spearow", listOf<String>("Normal", "Flying"), "Eats bugs in grassy areas. It has to flap its short wings at high speed to stay airborne.", R.drawable.spearow),
            Pkmn(22, "Fearow", listOf<String>("Normal", "Flying"), "With its huge and magnificent wings, it can keep aloft without ever having to land for rest.", R.drawable.fearow),
            Pkmn(23, "Ekans", listOf<String>("Poison"), "Moves silently and stealthily. Eats the eggs of birds, such as PIDGEY and SPEAROW, whole.", R.drawable.ekans),
            Pkmn(24, "Arbok", listOf<String>("Poison"), "It is rumored that the ferocious warning markings on its belly differ from area to area.", R.drawable.arbok),
            Pkmn(25, "Pikachu", listOf<String>("Electric"), "0025", R.drawable.pikachu),
            Pkmn(26, "Raichu", listOf<String>("Electric"), "0026", R.drawable.raichu),
            Pkmn(27, "Sandshrew", listOf<String>("Ground"), "0027", R.drawable.sandshrew),
            Pkmn(28, "Sandslash", listOf<String>("Ground"), "0028", R.drawable.sandslash),
            Pkmn(29, "Nidoran♀ (female)", listOf<String>("Poison"), "Although small, its venomous barbs render this POKéMON dangerous. The female has smaller horns.", R.drawable.nidoran_f),
            Pkmn(30, "Nidorina", listOf<String>("Poison"), "The female’s horn develops slowly. Prefers physical attacks such as clawing and biting.", R.drawable.nidorina),
            Pkmn(31, "Nidoqueen", listOf<String>("Poison", "Ground"), "Its hard scales provide strong protection. It uses its hefty bulk to execute powerful moves.", R.drawable.nidoqueen),
            Pkmn(32, "Nidoran♂ (male)", listOf<String>("Poison"), "Stiffens its ears to sense danger. The larger its horns, the more powerful its secreted venom.", R.drawable.nidoran_m),
            Pkmn(33, "Nidorino", listOf<String>("Poison"), "An aggressive POKéMON that is quick to attack. The horn on its head secretes a powerful venom.", R.drawable.nidorino),
            Pkmn(34, "Nidoking", listOf<String>("Poison", "Ground"), "It uses its powerful tail in battle to smash, constrict, then break the prey’s bones.", R.drawable.nidoking),
            Pkmn(35, "Clefairy", listOf<String>("Fairy"), "Its magical and cute appeal has many admirers. It is rare and found only in certain areas.", R.drawable.clefairy),
            Pkmn(36, "Clefable", listOf<String>("Fairy"), "A timid fairy POKéMON that is rarely seen. It will run and hide the moment it senses people.", R.drawable.clefable),
            Pkmn(37, "Vulpix", listOf<String>("Fire"), "0037", R.drawable.vulpix),
            Pkmn(38, "Ninetales", listOf<String>("Fire"), "0038", R.drawable.ninetales),
            Pkmn(39, "Jigglypuff", listOf<String>("Normal", "Fairy"), "When its huge eyes light up, it sings a mysteriously soothing melody that lulls its enemies to sleep.", R.drawable.jigglypuff),
            Pkmn(40, "Wigglytuff", listOf<String>("Normal", "Fairy"), "The body is soft and rubbery. When angered, it will suck in air and inflate itself to an enormous size.", R.drawable.wigglytuff),
            Pkmn(41, "Zubat", listOf<String>("Poison", "Flying"), "Forms colonies in perpetually dark places. Uses ultrasonic waves to identify and approach targets.", R.drawable.zubat),
            Pkmn(42, "Golbat", listOf<String>("Poison", "Flying"), "Once it strikes, it will not stop draining energy from the victim even if it gets too heavy to fly.", R.drawable.golbat),
            Pkmn(43, "Oddish", listOf<String>("Grass", "Poison"), "During the day, it keeps its face buried in the ground. At night, it wanders around sowing its seeds.", R.drawable.oddish),
            Pkmn(44, "Gloom", listOf<String>("Grass", "Poison"), "The fluid that oozes from its mouth isn’t drool. It is a nectar that is used to attract prey.", R.drawable.gloom),
            Pkmn(45, "Vileplume", listOf<String>("Grass", "Poison"), "The larger its petals, the more toxic pollen it contains. Its big head is heavy and hard to hold up.", R.drawable.vileplume),
            Pkmn(46, "Paras", listOf<String>("Bug", "Grass"), "Burrows to suck tree roots. The mushrooms on its back grow by drawing nutrients from the bug host.", R.drawable.paras),
            Pkmn(47, "Parasect", listOf<String>("Bug", "Grass"), "A host-parasite pair in which the parasite mushroom has taken over the host bug. Prefers damp places.", R.drawable.parasect),
            Pkmn(48, "Venonat", listOf<String>("Bug", "Poison"), "Lives in the shadows of tall trees where it eats insects. It is attracted by light at night.", R.drawable.venonat),
            Pkmn(49, "Venomoth", listOf<String>("Bug", "Poison"), "The dust-like scales covering its wings are color coded to indicate the kinds of poison it has.", R.drawable.venomoth),
            Pkmn(50, "Diglett", listOf<String>("Ground"), "0050", R.drawable.diglett),
            Pkmn(51, "Dugtrio", listOf<String>("Ground"), "0051", R.drawable.dugtrio),
            Pkmn(52, "Meowth", listOf<String>("Normal"), "0052", R.drawable.meowth),
            Pkmn(53, "Persian", listOf<String>("Normal"), "0053", R.drawable.persian),
            Pkmn(54, "Psyduck", listOf<String>("Water"), "While lulling its enemies with its vacant look, this wily POKéMON will use psychokinetic powers.", R.drawable.psyduck),
            Pkmn(55, "Golduck", listOf<String>("Water"), "Often seen swimming elegantly by lake shores. It is often mistaken for the Japanese monster, Kappa.", R.drawable.golduck),
            Pkmn(56, "Mankey", listOf<String>("Fighting"), "Extremely quick to anger. It could be docile one moment then thrashing away the next instant.", R.drawable.mankey),
            Pkmn(57, "Primeape", listOf<String>("Fighting"), "Always furious and tenacious to boot. It will not abandon chasing its quarry until it is caught.", R.drawable.primeape),
            Pkmn(58, "Growlithe", listOf<String>("Fire"), "0058", R.drawable.growlithe),
            Pkmn(59, "Arcanine", listOf<String>("Fire"), "0059", R.drawable.arcanine),
            Pkmn(60, "Poliwag", listOf<String>("Water"), "Its newly grown legs prevent it from running. It appears to prefer swimming than trying to stand.", R.drawable.poliwag),
            Pkmn(61, "Poliwhirl", listOf<String>("Water"), "Capable of living in or out of water. When out of water, it sweats to keep its body slimy.", R.drawable.poliwhirl),
            Pkmn(62, "Poliwrath", listOf<String>("Water", "Fighting"), "An adept swimmer at both the front crawl and breast stroke. Easily overtakes the best human swimmers.", R.drawable.poliwrath),
            Pkmn(63, "Abra", listOf<String>("Psychic"), "Using its ability to read minds, it will identify impending danger and TELEPORT to safety.", R.drawable.abra),
            Pkmn(64, "Kadabra", listOf<String>("Psychic"), "It emits special alpha waves from its body that induce headaches just by being close by.", R.drawable.kadabra),
            Pkmn(65, "Alakazam", listOf<String>("Psychic"), "0065", R.drawable.alakazam),
            Pkmn(66, "Machop", listOf<String>("Fighting"), "Loves to build its muscles. It trains in all styles of martial arts to become even stronger.", R.drawable.machop),
            Pkmn(67, "Machoke", listOf<String>("Fighting"), "Its muscular body is so powerful, it must wear a power save belt to be able to regulate its motions.", R.drawable.machoke),
            Pkmn(68, "Machamp", listOf<String>("Fighting"), "Using its heavy muscles, it throws powerful punches that can send the victim clear over the horizon.", R.drawable.machamp),
            Pkmn(69, "Bellsprout", listOf<String>("Grass", "Poison"), "A carnivorous POKéMON that traps and eats bugs. It uses its root feet to soak up needed moisture.", R.drawable.bellsprout),
            Pkmn(70, "Weepinbell", listOf<String>("Grass", "Poison"), "It spits out POISONPOWDER to immobilize the enemy and then finishes it with a spray of ACID.", R.drawable.weepinbell),
            Pkmn(71, "Victreebel", listOf<String>("Grass", "Poison"), "Said to live in huge colonies deep in jungles, although no one has ever returned from there.", R.drawable.victreebel),
            Pkmn(72, "Tentacool", listOf<String>("Water", "Poison"), "Drifts in shallow seas. Anglers who hook them by accident are often punished by its stinging acid.", R.drawable.tentacool),
            Pkmn(73, "Tentacruel", listOf<String>("Water", "Poison"), "The tentacles are normally kept short. On hunts, they are extended to ensnare and immobilize prey.", R.drawable.tentacruel),
            Pkmn(74, "Geodude", listOf<String>("Rock", "Ground"), "0074", R.drawable.geodude),
            Pkmn(75, "Graveler", listOf<String>("Rock", "Ground"), "0075", R.drawable.graveler),
            Pkmn(76, "Golem", listOf<String>("Rock", "Ground"), "0076", R.drawable.golem),
            Pkmn(77, "Ponyta", listOf<String>("Fire"), "0077", R.drawable.ponyta),
            Pkmn(78, "Rapidash", listOf<String>("Fire"), "0078", R.drawable.rapidash),
            Pkmn(79, "Slowpoke", listOf<String>("Water", "Psychic"), "0079", R.drawable.slowpoke),
            Pkmn(80, "Slowbro", listOf<String>("Water", "Psychic"), "0080", R.drawable.slowbro),
            Pkmn(81, "Magnemite", listOf<String>("Electric", "Steel"), "Uses anti-gravity to stay suspended. Appears without warning and uses THUNDER WAVE and similar moves.", R.drawable.magnemite),
            Pkmn(82, "Magneton", listOf<String>("Electric", "Steel"), "Formed by several MAGNEMITEs linked together. They frequently appear when sunspots flare up.", R.drawable.magneton),
            Pkmn(83, "Farfetch'd", listOf<String>("Normal", "Flying"), "0083", R.drawable.farfetchd),
            Pkmn(84, "Doduo", listOf<String>("Normal", "Flying"), "A bird that makes up for its poor flying with its fast foot speed. Leaves giant footprints.", R.drawable.doduo),
            Pkmn(85, "Dodrio", listOf<String>("Normal", "Flying"), "Uses its three brains to execute complex plans. While two heads sleep, one head stays awake.", R.drawable.dodrio),
            Pkmn(86, "Seel", listOf<String>("Water"), "The protruding horn on its head is very hard. It is used for bashing through thick ice.", R.drawable.seel),
            Pkmn(87, "Dewgong", listOf<String>("Water", "Ice"), "Stores thermal energy in its body. Swims at a steady 8 knots even in intensely cold waters.", R.drawable.dewgong),
            Pkmn(88, "Grimer", listOf<String>("Poison"), "0088", R.drawable.grimer),
            Pkmn(89, "Muk", listOf<String>("Poison"), "0089", R.drawable.muk),
            Pkmn(90, "Shellder", listOf<String>("Water"), "Its hard shell repels any kind of attack. It is vulnerable only when its shell is open.", R.drawable.shellder),
            Pkmn(91, "Cloyster", listOf<String>("Water", "Ice"), "When attacked, it launches its horns in quick volleys. Its innards have never been seen.", R.drawable.cloyster),
            Pkmn(92, "Gastly", listOf<String>("Ghost", "Poison"), "Almost invisible, this gaseous POKéMON cloaks the target and puts it to sleep without notice.", R.drawable.gastly),
            Pkmn(93, "Haunter", listOf<String>("Ghost", "Poison"), "Because of its ability to slip through block walls, it is said to be from another dimension.", R.drawable.haunter),
            Pkmn(94, "Gengar", listOf<String>("Ghost", "Poison"), "0094", R.drawable.gengar),
            Pkmn(95, "Onix", listOf<String>("Rock", "Ground"), "As it grows, the stone portions of its body harden to become similar to a diamond, but colored black.", R.drawable.onix),
            Pkmn(96, "Drowzee", listOf<String>("Psychic"), "Puts enemies to sleep then eats their dreams. Occasionally gets sick from eating bad dreams.", R.drawable.drowzee),
            Pkmn(97, "Hypno", listOf<String>("Psychic"), "When it locks eyes with an enemy, it will use a mix of PSI moves such as HYPNOSIS and CONFUSION.", R.drawable.hypno),
            Pkmn(98, "Krabby", listOf<String>("Water"), "Its pincers are not only powerful weapons, they are used for balance when walking sideways.", R.drawable.krabby),
            Pkmn(99, "Kingler", listOf<String>("Water"), "The large pincer has 10000 hp of crushing power. However, its huge size makes it unwieldy to use.", R.drawable.kingler),
            Pkmn(100, "Voltorb", listOf<String>("Electric"), "0100", R.drawable.voltorb),
            Pkmn(101, "Electrode", listOf<String>("Electric"), "0101", R.drawable.electrode),
            Pkmn(102, "Exeggcute", listOf<String>("Grass", "Psychic"), "Often mistaken for eggs. When disturbed, they quickly gather and attack in swarms.", R.drawable.exeggcute),
            Pkmn(103, "Exeggutor", listOf<String>("Grass", "Psychic"), "0103", R.drawable.exeggutor),
            Pkmn(104, "Cubone", listOf<String>("Ground"), "Because it never removes its skull helmet, no one has ever seen this POKéMON’s real face.", R.drawable.cubone),
            Pkmn(105, "Marowak", listOf<String>("Ground"), "0105", R.drawable.marowak),
            Pkmn(106, "Hitmonlee", listOf<String>("Fighting"), "When in a hurry, its legs lengthen progressively. It runs smoothly with extra long, loping strides.", R.drawable.hitmonlee),
            Pkmn(107, "Hitmonchan", listOf<String>("Fighting"), "While apparently doing nothing, it fires punches in lightning fast volleys that are impossible to see.", R.drawable.hitmonchan),
            Pkmn(108, "Lickitung", listOf<String>("Normal"), "Its tongue can be extended like a chameleon’s. It leaves a tingling sensation when it licks enemies.", R.drawable.lickitung),
            Pkmn(109, "Koffing", listOf<String>("Poison"), "Because it stores several kinds of toxic gases in its body, it is prone to exploding without warning.", R.drawable.koffing),
            Pkmn(110, "Weezing", listOf<String>("Poison"), "0110", R.drawable.weezing),
            Pkmn(111, "Rhyhorn", listOf<String>("Ground", "Rock"), "Its massive bones are 1000 times harder than human bones. It can easily knock a trailer flying.", R.drawable.rhyhorn),
            Pkmn(112, "Rhydon", listOf<String>("Ground", "Rock"), "Protected by an armor-like hide, it is capable of living in molten lava of 3,600 degrees.", R.drawable.rhydon),
            Pkmn(113, "Chansey", listOf<String>("Normal"), "A rare and elusive POKéMON that is said to bring happiness to those who manage to get it.", R.drawable.chansey),
            Pkmn(114, "Tangela", listOf<String>("Grass"), "The whole body is swathed with wide vines that are similar to seaweed. Its vines shake as it walks.", R.drawable.tangela),
            Pkmn(115, "Kangaskhan", listOf<String>("Normal"), "0115", R.drawable.kangaskhan),
            Pkmn(116, "Horsea", listOf<String>("Water"), "Known to shoot down flying bugs with precision blasts of ink from the surface of the water.", R.drawable.horsea),
            Pkmn(117, "Seadra", listOf<String>("Water"), "Capable of swimming backwards by rapidly flapping its wing-like pectoral fins and stout tail.", R.drawable.seadra),
            Pkmn(118, "Goldeen", listOf<String>("Water"), "Its tail fin billows like an elegant ballroom dress, giving it the nickname of the Water Queen.", R.drawable.goldeen),
            Pkmn(119, "Seaking", listOf<String>("Water"), "In the autumn spawning season, they can be seen swimming powerfully up rivers and creeks.", R.drawable.seaking),
            Pkmn(120, "Staryu", listOf<String>("Water"), "An enigmatic POKéMON that can effortlessly regenerate any appendage it loses in battle.", R.drawable.staryu),
            Pkmn(121, "Starmie", listOf<String>("Water", "Psychic"), "Its central core glows with the seven colors of the rainbow. Some people value the core as a gem.", R.drawable.starmie),
            Pkmn(122, "Mr. Mime", listOf<String>("Psychic", "Fairy"), "0122", R.drawable.mr_mime),
            Pkmn(123, "Scyther", listOf<String>("Bug", "Flying"), "With ninja-like agility and speed, it can create the illusion that there is more than one.", R.drawable.scyther),
            Pkmn(124, "Jynx", listOf<String>("Ice", "Psychic"), "It seductively wiggles its hips as it walks. It can cause people to dance in unison with it.", R.drawable.jynx),
            Pkmn(125, "Electabuzz", listOf<String>("Electric"), "Normally found near power plants, they can wander away and cause major blackouts in cities.", R.drawable.electabuzz),
            Pkmn(126, "Magmar", listOf<String>("Fire"), "Its body always burns with an orange glow that enables it to hide perfectly among flames.", R.drawable.magmar),
            Pkmn(127, "Pinsir", listOf<String>("Bug"), "0127", R.drawable.pinsir),
            Pkmn(128, "Tauros", listOf<String>("Normal"), "0128", R.drawable.tauros),
            Pkmn(129, "Magikarp", listOf<String>("Water"), "In the distant past, it was somewhat stronger than the horribly weak descendants that exist today.", R.drawable.magikarp),
            Pkmn(130, "Gyarados", listOf<String>("Water", "Flying"), "0130", R.drawable.gyarados),
            Pkmn(131, "Lapras", listOf<String>("Water", "Ice"), "A POKéMON that has been overhunted almost to extinction. It can ferry people across the water.", R.drawable.lapras),
            Pkmn(132, "Ditto", listOf<String>("Normal"), "Capable of copying an enemy’s genetic code to instantly transform itself into a duplicate of the enemy.", R.drawable.ditto),
            Pkmn(133, "Eevee", listOf<String>("Normal"), "0133", R.drawable.eevee),
            Pkmn(134, "Vaporeon", listOf<String>("Water"), "Lives close to water. Its long tail is ridged with a fin which is often mistaken for a mermaid’s.", R.drawable.vaporeon),
            Pkmn(135, "Jolteon", listOf<String>("Electric"), "It accumulates negative ions in the atmosphere to blast out 10000-volt lightning bolts.", R.drawable.jolteon),
            Pkmn(136, "Flareon", listOf<String>("Fire"), "When storing thermal energy in its body, its temperature could soar to over 1600 degrees.", R.drawable.flareon),
            Pkmn(137, "Porygon", listOf<String>("Normal"), "A POKéMON that consists entirely of programming code. Capable of moving freely in cyberspace.", R.drawable.porygon),
            Pkmn(138, "Omanyte", listOf<String>("Rock", "Water"), "Although long extinct, in rare cases, it can be genetically resurrected from fossils.", R.drawable.omanyte),
            Pkmn(139, "Omastar", listOf<String>("Rock", "Water"), "A prehistoric POKéMON that died out when its heavy shell made it impossible to catch prey.", R.drawable.omastar),
            Pkmn(140, "Kabuto", listOf<String>("Rock", "Water"), "A POKéMON that was resurrected from a fossil found in what was once the ocean floor eons ago.", R.drawable.kabuto),
            Pkmn(141, "Kabutops", listOf<String>("Rock", "Water"), "Its sleek shape is perfect for swimming. It slashes prey with its claws and drains the body fluids.", R.drawable.kabutops),
            Pkmn(142, "Aerodactyl", listOf<String>("Rock", "Flying"), "0142", R.drawable.aerodactyl),
            Pkmn(143, "Snorlax", listOf<String>("Normal"), "Very lazy. Just eats and sleeps. As its rotund bulk builds, it becomes steadily more slothful.", R.drawable.snorlax),
            Pkmn(144, "Articuno", listOf<String>("Ice", "Flying"), "0144", R.drawable.articuno),
            Pkmn(145, "Zapdos", listOf<String>("Electric", "Flying"), "0145", R.drawable.zapdos),
            Pkmn(146, "Moltres", listOf<String>("Fire", "Flying"), "0146", R.drawable.moltres),
            Pkmn(147, "Dratini", listOf<String>("Dragon"), "Long considered a mythical POKéMON until recently when a small colony was found living underwater.", R.drawable.dratini),
            Pkmn(148, "Dragonair", listOf<String>("Dragon"), "A mystical POKéMON that exudes a gentle aura. Has the ability to change climate conditions.", R.drawable.dragonair),
            Pkmn(149, "Dragonite", listOf<String>("Dragon", "Flying"), "An extremely rarely seen marine POKéMON. Its intelligence is said to match that of humans.", R.drawable.dragonite),
            Pkmn(150, "Mewtwo", listOf<String>("Psychic"), "0150", R.drawable.mewtwo),
            Pkmn(151, "Mew", listOf<String>("Psychic"), "So rare that it is still said to be a mirage by many experts. Only a few people have seen it worldwide.", R.drawable.mew),
        )
    }
}